### ISSUE TITLE
Class OpenSwoole\Coroutine\WaitGroup not found

### ISSUE THREAD

**Issue by eqmaz** [openswoole/ext-openswoole#302]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
<?php
declare(strict_types=1);

use OpenSwoole\Coroutine\WaitGroup;

co::run(function() {
    $wg = new WaitGroup();

    $results = [];
    go(function () use ($wg, &$results) {
        $wg->add();
        co::sleep(3);
        $results[] = 'a';
        $wg->done();
    });

    go(function () use ($wg, &$results) {
        $wg->add();
        co::sleep(7);
        $results[] = 'b';
        $wg->done();
    });

    $wg->wait(10);
    var_dump($results);
});


```
2. What did you expect to see?
```
Program runs

```
3. What did you see instead?
```
PHP Fatal error:  Uncaught Error: Class "OpenSwoole\Coroutine\WaitGroup" not found

```
4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
22.0.0 (zts_build)

```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
ubuntu 22 php 8.1.14

```

You can also try the following OpenSwoole support channels:

* [Documentation](https://openswoole.com/docs) - Documentation for Open Swoole
* [Slack](https://goo.gl/forms/wooTTDmhbu30x4qC3) - Slack channel of Open Swoole
* [Discord](https://discord.gg/5QC57RNPpw) - Discord server of Open Swoole

**Comment by doubaokun** [comment]
It is available at OpenSwoole\Core\Coroutine\WaitGroup when you have openswoole\core library installed.

**Comment by eqmaz** [comment]
> 

...so for version 22.x + some of the functions have been moved out of the extension and into a supplementary composer package. Is the logic behind this move to keep the extension lean and as low level as possible? This move now adds an extra installation step, or invtes project-level re-implementation of these functions.

**Comment by doubaokun** [comment]
It is a part of the architect changes and openswoole\core allows you access more features. Docs: https://openswoole.com/docs/modules/swoole-coroutine-waitgroup
