### ISSUE TITLE
Method naming overlap prevent install/enable both swoole/openswoole simultaneously

### ISSUE THREAD

**Issue by yespire** [openswoole/ext-openswoole#306]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
install and enable both swoole and openswoole
```
2. What did you expect to see?
```
no warning, expect no method naming overlap
```
3. What did you see instead?
```
when run "php -v", warnings are shown:
PHP Warning:  Function registration failed - duplicate name - swoole_coroutine_create in Unknown on line 0
PHP Warning:  Function registration failed - duplicate name - swoole_coroutine_defer in Unknown on line 0
PHP Warning:  Function registration failed - duplicate name - swoole_coroutine_socketpair in Unknown on line 0
PHP Warning:  Function registration failed - duplicate name - swoole_test_kernel_coroutine in Unknown on line 0
PHP Warning:  Function registration failed - duplicate name - swoole_internal_call_user_shutdown_begin in Unknown on line 0
```
4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
latest openswoole
```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux dev-web 5.4.17-2136.302.6.1.el7uek.x86_64 #2 SMP Tue Dec 14 13:21:01 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by doubaokun** [comment]
You can’t use two extensions the same time

**Comment by yespire** [comment]
@doubaokun 

a)
Will openswoole rename all the "swoole_" methods?
Seeing a mixed of "swoole_" and "openswoole_" can be confusing and unsettling.

b)
> You can’t use two extensions the same time

I agree, it doesn't make sense to use both in the same application. However it does make sense to allow both swoole and openswoole to be installed as extension on the same host. For example, I may have 1 project using swoole, and another project using openswoole on my localhost.
