### ISSUE TITLE
Website documentation 404 page

### ISSUE THREAD

**Issue by martinhoffgenags** [openswoole/ext-openswoole#309]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
https://openswoole.com/docs/modules/swoole-coroutine-http-server

```
2. What did you expect to see?
```
Documentation


```
3. What did you see instead?
```
404

```
4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
latest
```

PS1... this feature sounds potentially very useful. 

PS2... General question, what is the project's recommended way to spawn an http server, but then also run additional event-loop based application logic in the background, which is not related to the http server?

**Comment by Ahmard** [comment]
Coroutine http server was added as an experimental server, it was deprecated and removed in OpenSwoole 22.
Check this for your reference: https://github.com/openswoole/ext-openswoole/releases/tag/v22.0.0
