### ISSUE TITLE
Composer Autoload for OpenSwoole\Server::stats()

### ISSUE THREAD

**Issue by ghnp5** [openswoole/ext-openswoole#317]
I'm running:

```
$response->end($server->stats(2)); // 2 - \OpenSwoole\Constant::STATS_OPENMETRICS doesn't exist
```

And I get the following:

> Uncaught ErrorException: OpenSwoole\Server::stats(): composer dependency required: composer install openswoole/core

I've already installed this package, and I'm including the composer's `autoload.php` at the top of my application:

```
require '/var/www/vendor/autoload.php';
```

But I'm still getting the same error.

How can I make this work? :)

Thank you.

**Comment by doubaokun** [comment]
Please make sure you have installed `composer install openswoole/core`.
