### ISSUE TITLE
OpenSwoole\Socket::EVENT_READ undefined

### ISSUE THREAD

**Issue by peliz** [openswoole/ext-openswoole#323]
Swoole\Event::add($process->pipe, function ($fp) {
                      //$var = inotify_read($fd);
                      echo fread($fp, 1024) . ' OOK';
                      OpenSwoole\Event::del($fp);
                      }, null, OpenSwoole\Socket::EVENT_READ);

OpenSwoole\Socket::EVENT_READ undefined

**Comment by twomiao** [comment]
It appears that openswoole is not being maintained anymore. I recommend using the official Swoole library at https://github.com/swoole.

**Comment by twomiao** [comment]
> ```
>                   Swoole\Event::add($process->pipe, function ($fp) {
>                   //$var = inotify_read($fd);
>                   echo fread($fp, 1024) . ' OOK';
>                   OpenSwoole\Event::del($fp);
>                   }, null, OpenSwoole\Socket::EVENT_READ);
> ```
> 
> OpenSwoole\Socket::EVENT_READ undefined

It appears that openswoole is not being maintained anymore. I recommend using the official Swoole library at https://github.com/swoole.

**Comment by doubaokun** [comment]
Please the docs at https://openswoole.com/docs/modules/swoole-event-add
