### ISSUE TITLE
Latest OpenSwoole Cygwin build with PHP8.1+

### ISSUE THREAD

**Issue by janreges** [openswoole/ext-openswoole#344]
Hi guys,

I've created a useful tool below (Website Crawler and Analyzer) that uses Swoole Coroutines.

The code is written in PHP 8.1 and I want it to be easy to run on all platforms without the need to use Docker or WSL on Windows. I chose Swoole (not OpenSwoole) because it offered a pre-built version with PHP 8.1 and Cygwin. I am currently completing an Electron application as a GUI for this tool for non-users. The Electron application components will also be packaged complete runtime with Swoole, for Windows with Cygwin version.

The problem is that Swoole often crashes in Cygwin if I use more than 1 worker. I believe that this reason has already been fixed in OpenSwoole.

I am therefore considering switching to OpenSwoole. Unfortunately, OpenSwoole has the last functional build on Cygwin with PHP 7.x.

Here is the last failed build: https://github.com/openswoole/ext-openswoole/actions/runs/6797370993/job/18479357578

Can I find someone willing to help me get a cygwin build of OpenSwoole with PHP 8.1+ version?

Thank you very much 🙏 

Docs (partly WIP): https://crawler.siteone.io/
Video demo: https://www.youtube.com/watch?v=qEiSTpb66nA
GitHub: https://github.com/janreges/siteone-crawler

**Comment by doubaokun** [comment]
It seems cygwin still not support PHP8: https://cygwin.com/packages/summary/php-src.html But you should be able to compile in cygwin now with version 22.1.1.
