### ISSUE TITLE
Will Openswoole get new updates?

### ISSUE THREAD

**Issue by jorgeluiz1586** [openswoole/ext-openswoole#368]
It's been a while since Openswoole has received any updates or corrections, we're on PHP version 8.4 and Openswoole is not compatible with this new version, Openswoole was gaining prominence over Swoole but the project has been without updates for a long time.

**Comment by doubaokun** [comment]
Yes. PHP 8.4 support will be available soon.

**Comment by doubaokun** [comment]
8.4 is supported on master branch now.
